### ISSUE TITLE
i have this problem

### ISSUE THREAD

**Issue by westlife767** [hwiyoung/Orthophoto_Maps#1]
hello,i use your  code to study,but i have this problem,can you tell me why?
this is problem:   NameError: name 'restored_image' is not defined 
this problem is appear this line:bbox = boundary(restored_image, eo, R, ground_height, pixel_size, focal_length)

**Comment by hwiyoung** [comment]
Hi

I ran the code and checked the line you said. But I haven't found any weird things.
Plz let me know the detailed error message or a captured image!

**Comment by westlife767** [comment]
I did not do any things when  I cloned it，the data was your provided in the file, I guess the data file called "Data" ,this is problem  picture:
<img width="1175" alt="WeChatbf46511cf6fd038083cf1207f33aab57" src="https://user-images.githubusercontent.com/15814051/62535978-5cdf3480-b87f-11e9-9b28-af93f5fb367f.png">

**Comment by hwiyoung** [comment]
I checked the lines you said again... but I can't find weird things
This is my command line messages corresponding to your comment

```
Read EOP - DJI_0390.txt
Latitude | Longitude | Height | Omega | Phi | Kappa
[34.727688, 127.724265, 215.054, 0.01757132685087435, 0.016296146434080866, -0.9285251137538453]
--- 0.056955814361572266 seconds ---
projectedCoord
--- 0.5344974994659424 seconds ---
backProjection
--- 2.6545419692993164 seconds ---
resample
--- 0.4365956783294678 seconds ---
Save the image in GeoTiff
--- 0.314708948135376 seconds ---
*** Processing time per each image
--- 4.566488981246948 seconds ---
```

Your image says the file you read is DJI_0390.JPG / DJI_0390.txt
How about in other files like DJI_0386, DJI_0387 etc.
These images have also same problems?
Plz let me know I have been checking the reason

**Comment by hwiyoung** [comment]
I closed this issue because of no response
