### ISSUE TITLE
Orthophoto coordinates are incorrect

### ISSUE THREAD

**Issue by dubing-bit** [hwiyoung/Orthophoto_Maps#18]
I successfully run the program, but the image coordinate system after loading in QGIS is not correct. May I ask why? (Using the example data provided in the repository)

**Comment by hwiyoung** [comment]
Hi

Could you explain in more detail?

The result file or screenshots can be helpful

**Comment by dubing-bit** [comment]
Maybe it was an accidental mistake, when I removed the principle code and redeployed it, it works fine. Thanks for your contribution!
