### ISSUE TITLE
Where can I get the required parameters( Omega | Phi | Kappa) from the DJI photos?

### ISSUE THREAD

**Issue by SandW** [hwiyoung/Orthophoto_Maps#2]
I use ExifTool to extract information from the DJI photo, however, I cannot find the corresponding parameters - Omega | Phi | Kappa. I guess they are the gimbal angles which represent the attitude of the camera. But they are not the same values.

**Comment by kikislater** [comment]
In the exifs
Example : 

`exiftool DJI_0009.jpg | grep Gimbal`

**Comment by hwiyoung** [comment]
@SandW As you said, the parameters - Omega | Phi | Kappa isn't originated from the metadata like exif. It's originated from some computation, which is photogrammetry processing like @kikislater said.

I'm planning to add a module to convert roll/pitch/yaw to omega/phi/kappa using calibration parameters based on DJI Mavic. The parameters are different to drones, but I'm gonna add others ASAP.

**Comment by kikislater** [comment]
In other words, you need to compute a rotation matrix, then you could find Omega Phi Kappa.

Here a code example of rotation matrix : 

https://github.com/nasa/georef_geocamutilweb/blob/5eb4bb768c946c16d703b63cf3fd62394ddfacba/geocamUtil/registration.py

Rotation matrix computed from Roll Pitch Yaw
```
    c = np.cos(yaw)
    s = np.sin(yaw)
    RZ[0,0] = c
    RZ[0,1] = -s
    RZ[1,0] = s
    RZ[1,1] = c
    RZ[2,2] = 1

    c = np.cos(pitch)
    s = np.sin(pitch)
    RY[0,0] = c
    RY[0,2] = s
    RY[2,0] = -s
    RY[2,2] = c
    RY[1,1] = 1
    
    c = np.cos(roll)
    s = np.sin(roll)
    RX[1,1] = c 
    RX[1,2] = -s
    RX[2,1] = s
    RX[2,2] = c
    RX[0,0] = 1
```

And Rotation Matrix to OPK : 

```
    """
    Converts rotation matrix into euler angles
    """
    phi = 0
    omega = np.arcsin(-rotMatrix.item(2,0))
    kappa = None;
    
    if np.absolute(omega - (math.pi/2.0)) < 0.0000001:
        kappa = np.arctan2(rotMatrix.item(1,2), rotMatrix.item(0,2))
    if np.absolute(omega + (math.pi/2.0)) < 0.0000001:
        kappa = np.arctan2(-rotMatrix.item(1,2), -rotMatrix.item(0,2))
    else:
        phi = np.arctan2(rotMatrix.item(2,1), rotMatrix.item(2,2))
        kappa = np.arctan2(rotMatrix.item(1,0), rotMatrix.item(0,0))
    return [phi, omega, kappa]
```

Looking forward to watch your code @hwiyoung ;-)

**Comment by SandW** [comment]
OK, thanks!

**Comment by hwiyoung** [comment]
I'm sorry for my late answer

I've tested the code that converting gimbal roll/pitch/yaw to omega/phi/kappa
You can check the result by executing Orthophoto_DG.py

Orthophoto_DG needs additional modifications but for now you can check the result :)

Again sorry for the delay

**Comment by Zhugguanglei** [comment]
> I'm sorry for my late answer
> 
> I've tested the code that converting gimbal roll/pitch/yaw to omega/phi/kappa
> You can check the result by executing Orthophoto_DG.py
> 
> Orthophoto_DG needs additional modifications but for now you can check the result :)
> 
> Again sorry for the delay

Hi，hwiyoung.
I want to use Orthophoto_DG.py,but I didn't find it, did you move it to other places?

**Comment by hwiyoung** [comment]
@Zhugguanglei, I converted the main code from Orthophoto_DG.py to main_dg.py

You can check in README. Please check the usage section :)
