### ISSUE TITLE
How to process a batch of photos

### ISSUE THREAD

**Issue by Stephen-Z** [hwiyoung/Orthophoto_Maps#3]
We usually use a drone to shoot orthographic picture, and it will take a bundle of photos in one orthographic shooting task. So, May I ask how can I run your code to process these photos into a single tif file?

**Comment by hwiyoung** [comment]
Hi Stephen

I didn't fully understand your saying, so I wanna ask something

Are you saying you want to generate individual orthophotos from bundle of photos like files in my Data folder?
If then and you are using photos from DJI drones, you can do this by just executing `Orthophoto_DG.py`.

But... for now you have to designate the folder where photos are

Detailed information about the data folder is as below

- line 14, `Orthophoto_DG.py`

`    for root, dirs, files in os.walk('../00_data/sample_dji'):`

Of course, I have a plan to arrange this configurations haha

**Comment by Stephen-Z** [comment]
Hi hwiyong, Thanks for your reply, maybe individual orthophotos is not what I am looking for, I tried to run Orthophoto.py and I saw it generate five tif files(individual orthophotos), but actually, I want to generate a huge, single orthophoto from bundle of photos, each photo in the bundle just like a piece of puzzle, then put them together to the single tif file. Maybe I can show you some screenshot tomorrow for demonstration if you feel hard to undenstand my poor english haha~

**Comment by Stephen-Z** [comment]
Ok, seems like I can merge all individual tif files into one tif file with gdal_merge.py script, I will try that later.
