### ISSUE TITLE
about requirements

### ISSUE THREAD

**Issue by sevilmisbelkis** [hwiyoung/Orthophoto_Maps#4]
hi, can you share requirements.txt?

 I have issues with python 3.8 which version should I use? 

I was searching simple orthophoto generator project. I think this can meet with my requirements. thanks

**Comment by hwiyoung** [comment]
I uploaded the requirements by environment.yaml in conda

It is valid in python 3.8, Ubuntu 18.04

Please check the updated README

Thanks!
