### ISSUE TITLE
Hi hwiyoung, if I want to stitch my own pic. What should I do?

### ISSUE THREAD

**Issue by li1997522** [hwiyoung/Orthophoto_Maps#5]
I'm already building this project. But I don't know how to change the input, and what command to use in this project? Would you like to help me? Thank

**Comment by hwiyoung** [comment]
Hi li1997522

So I think you have 3 questions
1. stitching
2. changing the input
3. command to use

Here is my answers
1. Unfortunately this project doesn't have stitching. But I'm considering to add
2. A path of input is in input_foler in main_dg.py(https://github.com/hwiyoung/Orthophoto_Maps/blob/master/main_dg.py#L13). I'm also about to change the way of configuration
3. It is same as in README.
`python main_dg.py`

Thanks

**Comment by li1997522** [comment]
Hi, Thanks for your answer! It helps me a lot. I was wrong. 
I thought it could stitch pictures. I'd like to find a way to stitch drone pictures. We use the cattle farming method to collect pictures. I would like to stitch those pics to get a panoramic image with wide range. 
Do you know any good code to solve my problem? 
Thanks!

**Comment by hwiyoung** [comment]
If you want to stitch images, I think you can use the conventional panorama or stitching algorithm using OpenCV like... this?... https://pyimagesearch.com/2018/12/17/image-stitching-with-opencv-and-python/

But if you want to mosaic or merge orthophotos, I think you can use some geographic libraries like GDAL or Orfeo
Here are some links you can check

- https://gdal.org/programs/gdal_merge.html
- https://gdal.org/programs/gdalwarp.html
- https://www.orfeo-toolbox.org/CookBook/Applications/app_Mosaic.html

Feel free to ask me :) Thanks
