### ISSUE TITLE
On the acquisition of longitude and latitude

### ISSUE THREAD

**Issue by ShangPH** [hwiyoung/Orthophoto_Maps#6]
Hello, thank you for your excellent work. I am using this project. Is there any way to obtain the longitude and latitude coordinates of the image after ortho transformation?

**Comment by hwiyoung** [comment]
Hi, thank you for your interest

All generated orthophotos are georeferenced, you can check coordinates just loading orthophotos using GIS SW like QGIS
I'm checking a coordinates of an orthophoto using QGIS for now

Thanks

**Comment by ShangPH** [comment]
Thank you for your answer. 
In addition, I would like to ask whether the project can output the geographic coordinate information of Orthophoto from the code？
