### ISSUE TITLE
geotiff save

### ISSUE THREAD

**Issue by xxAla** [hwiyoung/Orthophoto_Maps#7]
Hi Hwiyoung Kim. i'm having problems with library establisments. for example, i could not install the "pyexiv2x" library in the exifdata module in the main_dg code, it gave a lot of errors. do you have any suggestions for me about installing the libraries? i can't  run the code without them. i have never been able to run it. thanks in advance :)

**Comment by xxAla** [comment]
Again Hi :) what library did you use to run "getExif"? cannot identify. i took care of other libraries

**Comment by hwiyoung** [comment]
Hi xxAla

Do you mean you can't save the result file, an orthophoto? or you can't identify where it is?

If you ran the code without error, you should have the result files :)

**Comment by xxAla** [comment]
the code is working yes, it even says saved as geotiff but it never shows where it saves :) so this code is scanning photos after all. so how can i see the result output i.e. orthophoto image? i would really apreciate if you help :)

**Comment by hwiyoung** [comment]
If you did't edit the code about a path of dst files, the results, orthophotos, have to be in the same position as `main_dg.py`

Here is the line of the code about a path of dst files
https://github.com/hwiyoung/Orthophoto_Maps/blob/master/main_dg.py#L29

**Comment by xxAla** [comment]
i worked with ortophoto.py instead of main.dg.py

**Comment by hwiyoung** [comment]
Oh please execute `main_dg.py`. It is the execution code

Orthophoto.py will be deprecated

Im gonna arrange the codes haha
Please refer to Readme :)

**Comment by xxAla** [comment]
mianhaeyo :') i didin't notice because i was working hard. it didin't recognize line 49, namely "rpy_to_opk" this time :) how did u install it?

**Comment by hwiyoung** [comment]
rpy_to_opk is a function from `EoData,py`
https://github.com/hwiyoung/Orthophoto_Maps/blob/master/module/EoData.py#L116

If you install libraries in environment.yaml, you don't need to do any other installation

Please check this
https://github.com/hwiyoung/Orthophoto_Maps#installation
```
conda env create -f environment.yaml
conda activate orthophoto
```

**Comment by xxAla** [comment]
thank u for help, really sorry if i bother u. i followed the steps you said. i can't get inside the loop which is line 20 in main.dg. what do you think could be reason? why doesn't the code read it?

**Comment by hwiyoung** [comment]
Line from 13 to 18 is a configuration part. Before going in to process you should set an input folder path, ground height, sensor width and espg.

If you can't get inside the loop, you have to check whether "input_foloder" has images. If not, the loop won't work

And if there is an error message, I can figure it out quickly what th problem is :)

**Comment by xxAla** [comment]
if you have a gmail account i want to send you a picture i took a screenshoot. i hope you understand better what i mean. i can output that lines 13-18 are working but not counting the loop. i think it's evening now in Korea, sorry if i bother u

**Comment by hwiyoung** [comment]
Do you have a directory named "sample_dji"?

It's a kind of an example, you should modify with regard to your directory

Or just change "../00_data/sample_dji" to "Data". It will work

The loop needs data

And... I'm gonna change the way to set the configurations haha

**Comment by xxAla** [comment]
Gwiyoung i'm a little embarrassed but okay :)) you're great thank u, it really worked. can i ask one last thing??
