### ISSUE TITLE
Problem of geolocalisation

### ISSUE THREAD

**Issue by sbonaime** [hwiyoung/Orthophoto_Maps#9]
Hi,

I run your code without problem, but the result is not correct : 
- tiff images are not well referenced 
- tiff  images do not overlap
- tiff  images are not well orientated 

My parameters : 
- PH4 RTK
- epsg 4471
- flat landscape, seashore at low tide

Can I share you privately some images ? 
Thanks

**Comment by hwiyoung** [comment]
Hi

Sure. If you send me data, I'll check

Link, email anything is good :)
